[project]
name = "duckpipe"
version = "0.1.0"
description = "."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "numpy>=1.26.3",
    "pandas>=2.2.0",
    "pytest", 
    "python-dotenv",
    "scipy>=1.14.1",
    "tqdm",
    "typeguard", 
]